using CSV, DataFrames
save_path = "/home/quiarosa/AQ_research/Non_Intrusive_RB_MT/test"

M1=DataFrame(M, :auto)
M2=DataFrame(M_smooth, :auto)
S1=DataFrame(S_random, :auto)
S2=DataFrame(S_smooth, :auto)
S1_norm=DataFrame(Snorm_random, :auto)
S2_norm=DataFrame(Snorm_smooth, :auto)
U1=DataFrame(Ur, :auto)
U2=DataFrame(Us, :auto)
A1=DataFrame(A_rand, :auto)
A2=DataFrame(A_smooth, :auto)

pathM1 = joinpath(save_path,"M1.csv")
pathM2 = joinpath(save_path,"M2.csv")
pathS1 = joinpath(save_path,"S1.csv")
pathS2 = joinpath(save_path,"S2.csv")
pathS1_norm = joinpath(save_path,"S1_norm.csv")
pathS2_norm = joinpath(save_path,"S2_norm.csv")
pathU1 = joinpath(save_path,"U1.csv")
pathU2 = joinpath(save_path,"U2.csv")
pathA1 = joinpath(save_path,"A1.csv")
pathA2 = joinpath(save_path,"A2.csv")
CSV.write(pathM1, M1)
CSV.write(pathM2, M2)
CSV.write(pathS1, S1)
CSV.write(pathS2, S2)
CSV.write(pathS1_norm, S1_norm)
CSV.write(pathS2_norm, S2_norm)
CSV.write(pathU1, U1)
CSV.write(pathU2, U2)
CSV.write(pathA1, A1)
CSV.write(pathA2, A2)

